-- Ross Nelson CSC352 Assignment 1
-- January 13th 2020

-- 1.
SELECT ENAME, SAL, HIREDATE 
FROM EMP 
WHERE (COMM <= 0 OR COMM IS NULL)
AND SAL < 2000;

-- 2.
SELECT EMP.ENAME, EMP.SAL, DEPT.DNAME
FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
WHERE (COMM <= 0 OR COMM is null)
AND SAL < 2000;

-- 3.
SELECT A.ENAME, A.SAL, B.ENAME, B.SAL
FROM EMP A, EMP B
WHERE A.MGR = B.EMPNO
AND A.DEPTNO = 30;

-- 4.
SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO;

-- 5.
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID >= 0
GROUP BY DEPARTMENT_ID;

-- 6.
SELECT A.LAST_NAME, A.FIRST_NAME, B.LAST_NAME
FROM EMPLOYEES A, EMPLOYEES B
WHERE A.MANAGER_ID = B.EMPLOYEE_ID
AND A.DEPARTMENT_ID IS NULL;

-- 7.
SELECT DEPARTMENT_ID, MAX(SALARY + ( NVL(COMMISSION_PCT, 0) * SALARY)) AS HIGHEST_INCOME, MIN(SALARY) AS LOWEST_INCOME
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--8.
DECLARE
    EMP_NAME VARCHAR2(15);
BEGIN
    SELECT ENAME
    INTO EMP_NAME
    FROM EMP
    WHERE EMPNO = 7839;
    DBMS_OUTPUT.PUT_LINE(EMP_NAME);
END;